// Country code to flag emoji mapping
export const getCountryFlag = (countryCode: string): string => {
  if (!countryCode || countryCode.length !== 2) return '';
  
  // Convert country code to flag emoji
  const flagOffset = 0x1F1E6 - 65; // A = 65, 🇦 = 0x1F1E6
  const firstChar = countryCode.toUpperCase().charCodeAt(0) + flagOffset;
  const secondChar = countryCode.toUpperCase().charCodeAt(1) + flagOffset;
  
  return String.fromCodePoint(firstChar, secondChar);
};

// Get flag by country name (fallback)
export const getCountryFlagByName = (countryName: string): string => {
  const countryToCode: Record<string, string> = {
    'United States': 'US',
    'United Kingdom': 'GB',
    'India': 'IN',
    'Canada': 'CA',
    'Australia': 'AU',
    'Germany': 'DE',
    'France': 'FR',
    'Japan': 'JP',
    'China': 'CN',
    'Brazil': 'BR',
    'Mexico': 'MX',
    'Italy': 'IT',
    'Spain': 'ES',
    'Netherlands': 'NL',
    'Sweden': 'SE',
    'Norway': 'NO',
    'Denmark': 'DK',
    'Finland': 'FI',
    'Switzerland': 'CH',
    'Austria': 'AT',
    'Belgium': 'BE',
    'Portugal': 'PT',
    'Ireland': 'IE',
    'New Zealand': 'NZ',
    'South Africa': 'ZA',
    'Singapore': 'SG',
    'South Korea': 'KR',
    'Thailand': 'TH',
    'Malaysia': 'MY',
    'Indonesia': 'ID',
    'Philippines': 'PH',
    'Vietnam': 'VN',
    'United Arab Emirates': 'AE',
    'Saudi Arabia': 'SA',
    'Egypt': 'EG',
    'Turkey': 'TR',
    'Russia': 'RU',
    'Poland': 'PL',
    'Czech Republic': 'CZ',
    'Hungary': 'HU',
    'Romania': 'RO',
    'Bulgaria': 'BG',
    'Croatia': 'HR',
    'Slovenia': 'SI',
    'Slovakia': 'SK',
    'Lithuania': 'LT',
    'Latvia': 'LV',
    'Estonia': 'EE',
    'Ukraine': 'UA',
    'Belarus': 'BY',
    'Moldova': 'MD',
    'Argentina': 'AR',
    'Chile': 'CL',
    'Colombia': 'CO',
    'Peru': 'PE',
    'Venezuela': 'VE',
    'Ecuador': 'EC',
    'Uruguay': 'UY',
    'Paraguay': 'PY',
    'Bolivia': 'BO',
    'Costa Rica': 'CR',
    'Panama': 'PA',
    'Guatemala': 'GT',
    'Honduras': 'HN',
    'El Salvador': 'SV',
    'Nicaragua': 'NI',
    'Jamaica': 'JM',
    'Dominican Republic': 'DO',
    'Cuba': 'CU',
    'Haiti': 'HT',
    'Puerto Rico': 'PR',
    'Bahamas': 'BS',
    'Barbados': 'BB',
    'Trinidad and Tobago': 'TT',
    'Grenada': 'GD',
    'Saint Lucia': 'LC',
    'Saint Vincent and the Grenadines': 'VC',
    'Antigua and Barbuda': 'AG',
    'Saint Kitts and Nevis': 'KN',
    'Dominica': 'DM',
    'Belize': 'BZ',
    'Guyana': 'GY',
    'Suriname': 'SR',
    'French Guiana': 'GF',
    'Israel': 'IL',
    'Jordan': 'JO',
    'Lebanon': 'LB',
    'Syria': 'SY',
    'Iraq': 'IQ',
    'Iran': 'IR',
    'Afghanistan': 'AF',
    'Pakistan': 'PK',
    'Bangladesh': 'BD',
    'Sri Lanka': 'LK',
    'Nepal': 'NP',
    'Bhutan': 'BT',
    'Maldives': 'MV',
    'Myanmar': 'MM',
    'Cambodia': 'KH',
    'Laos': 'LA',
    'Mongolia': 'MN',
    'North Korea': 'KP',
    'Taiwan': 'TW',
    'Hong Kong': 'HK',
    'Macau': 'MO',
    'Brunei': 'BN',
    'East Timor': 'TL',
    'Papua New Guinea': 'PG',
    'Fiji': 'FJ',
    'Solomon Islands': 'SB',
    'Vanuatu': 'VU',
    'New Caledonia': 'NC',
    'French Polynesia': 'PF',
    'Samoa': 'WS',
    'Tonga': 'TO',
    'Kiribati': 'KI',
    'Palau': 'PW',
    'Marshall Islands': 'MH',
    'Micronesia': 'FM',
    'Nauru': 'NR',
    'Tuvalu': 'TV',
    'Cook Islands': 'CK',
    'Niue': 'NU',
    'American Samoa': 'AS',
    'Guam': 'GU',
    'Northern Mariana Islands': 'MP',
    'Qatar': 'QA',
    'Kuwait': 'KW',
    'Bahrain': 'BH',
    'Oman': 'OM',
    'Yemen': 'YE',
    'Morocco': 'MA',
    'Algeria': 'DZ',
    'Tunisia': 'TN',
    'Libya': 'LY',
    'Sudan': 'SD',
    'South Sudan': 'SS',
    'Ethiopia': 'ET',
    'Eritrea': 'ER',
    'Djibouti': 'DJ',
    'Somalia': 'SO',
    'Kenya': 'KE',
    'Uganda': 'UG',
    'Tanzania': 'TZ',
    'Rwanda': 'RW',
    'Burundi': 'BI',
    'Democratic Republic of the Congo': 'CD',
    'Republic of the Congo': 'CG',
    'Central African Republic': 'CF',
    'Chad': 'TD',
    'Cameroon': 'CM',
    'Equatorial Guinea': 'GQ',
    'Gabon': 'GA',
    'São Tomé and Príncipe': 'ST',
    'Nigeria': 'NG',
    'Niger': 'NE',
    'Mali': 'ML',
    'Burkina Faso': 'BF',
    'Ivory Coast': 'CI',
    'Ghana': 'GH',
    'Togo': 'TG',
    'Benin': 'BJ',
    'Guinea': 'GN',
    'Guinea-Bissau': 'GW',
    'Sierra Leone': 'SL',
    'Liberia': 'LR',
    'Senegal': 'SN',
    'Gambia': 'GM',
    'Mauritania': 'MR',
    'Cape Verde': 'CV',
    'Madagascar': 'MG',
    'Mauritius': 'MU',
    'Seychelles': 'SC',
    'Comoros': 'KM',
    'Zambia': 'ZM',
    'Zimbabwe': 'ZW',
    'Botswana': 'BW',
    'Namibia': 'NA',
    'Lesotho': 'LS',
    'Swaziland': 'SZ',
    'Malawi': 'MW',
    'Mozambique': 'MZ',
    'Angola': 'AO',
  };

  const code = countryToCode[countryName];
  return code ? getCountryFlag(code) : '';
};